### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#1]
Create landing page with four areas in relation to aviation.

Suggestions:
-Civil Aviation
-Military Aviation
-Cargo and transport
-Airshows

Suggestions?

**Comment by axd1967** [comment]
in case you want alternatives:
- aviation
- music
- programming
- board games
- sports

**Comment by ZiggyMaes** [comment]
Merged 08e782a.
