### ISSUE TITLE
Project Finalization

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#16]
These tasks should be performed as the last step before project finalization and submission:
- [x] Document each feature, bug and general questions. 
- [x] Also describe what feature I'm most proud of, and what feature took most of my time.
- [x] All Github issues closed?
- [x] Create 3 users for testing: user, super-user, administrator and mention them in documentation.
- [ ] review/update analysis diagrams, generate implementation diagrams (if you have time and the tools to generate UML from your code).

**Comment by axd1967** [comment]
je kan checkboxes gebruiken:
- [x] een
- [x] twee
- [x] drie...

**Comment by ZiggyMaes** [comment]
Awesome!

**Comment by axd1967** [comment]
- [x] activate DOCENT password

**Comment by axd1967** [comment]
- [x] add more detailed domain content (#19 is for short, test data)

**Comment by ZiggyMaes** [comment]
I'd rather add the content early on. That makes it easy for me to wrap some CSS around the data. Waiting until the deadline milestone to add final data worries me a bit?

**Comment by axd1967** [comment]
ok.

but great content without a working server is also useless. so just add a few "placeholders" (phrases, images), and focus on a working system. but you will indeed need extra time to refine the content, but don't work on that for now.

**Comment by ZiggyMaes** [comment]
I'll put content in week 4 then.

**Comment by axd1967** [comment]
for the presentation (see item 3 in [pdf](https://github.com/ZiggyMaes/NMCT-Server-Side-Applications/blob/39dce06747a69997e28ab9eaef1591901f1f98a7/Project/Doc/Assignment.pdf)):
- [x] remember to include a planning + time spent. consider including an Excel file under [doc](https://github.com/ZiggyMaes/NMCT-Server-Side-Applications/tree/master/Project/Doc) and update it every time you work on issues. see branch CSV for an example .csv file (or any other data file you think can help, such as files managed by time tracking applications, etc).
- [x] TortoiseGit can also generate some statistics (I could generate them for you if you like):
  (there is a small [bug](https://gitlab.com/tortoisegit/tortoisegit/issues/2663))
  ![p3](https://cloud.githubusercontent.com/assets/3529789/11600247/c2c2a6c2-9acb-11e5-8de1-c768ece630f5.png)
  ![p4](https://cloud.githubusercontent.com/assets/3529789/11600248/c2c58068-9acb-11e5-8784-5f1ef4a14441.png)

**Comment by axd1967** [comment]
**Edit 11/12 ZM: moved to top comment**
 also, there is duplication between the diagrams and the .md files, maybe we can get rid of the .md files.

**Comment by axd1967** [comment]
- [x] remove strings like https://github.com/ZiggyMaes/NMCT-Server-Side-Applications/commit/d054ade9ed32e64047e752564e0c0d1271b9dc42#diff-af1274dbdfc5273a70675a25c5761452R17

(ben nu weg van de PC, vergeet niet uw milestones te sluiten)
