### ISSUE TITLE
Create own design/layout or use bootstrap?

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#17]
Should we build our own design or use a bootstrap theme?

**Comment by ZiggyMaes** [comment]
I'd spend a lot of time creating my own CSS, especially for scalability. Using a bootstrap theme and tweaking it would make more sense I think?

**Comment by axd1967** [comment]
not sure what this means, but maybe use template stuff first (but don't waste time), and if you have time, replace by hand (so you should add an issue to week 4 maybe, or deadline)

**Comment by ZiggyMaes** [comment]
Using bootstrap theme from 8c5eee48631aea244a90ea88ddaf30f22f4d7fda onwards. Will use placeholders for now, and focus on concrete design details toward the end of development.
