### ISSUE TITLE
Short inviting summary for each interest domain

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#18]
We can create a new, intermediary, page for this or use some kind of scroll-up boxes for this (http://student.howest.be/ziggy.maes/1NMCT/web/eindopdrachtweb/). I'd go with the boxes since that's pretty cool and unique. I'd appreciate some feedback on this.

**Comment by ZiggyMaes** [comment]
Feedback: @axd1967

**Comment by axd1967** [comment]
- looking good, especially because you have to display 4 areas = 2x2.
- keep it short, refine in #16 ?

**Comment by axd1967** [comment]
If you want, I could expand the Lorem Ipsum stuff (but don't count on it!).

**Comment by ZiggyMaes** [comment]
Feel free to do so whenever you see fit. I'm not expecting you to do so though ;).

**Comment by ZiggyMaes** [comment]
Thanks for the help! :)
