### ISSUE TITLE
Database schematics

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#2]
Create database schematics.

See scheme: [pic](https://github.com/ZiggyMaes/NMCT-Server-Side-Applications/blob/master/Project/Doc/Analysis/class_analysis.png)

**Comment by axd1967** [comment]
needs to complete #25 first

**Comment by ZiggyMaes** [comment]
See 4a238f3

**Comment by axd1967** [comment]
(if you like, you can add a link to the [pic](https://github.com/ZiggyMaes/NMCT-Server-Side-Applications/blob/master/Project/Doc/Analysis/class_analysis.png) in this issue top comment so you have a quick access)

**Comment by ZiggyMaes** [comment]
:+1:
