### ISSUE TITLE
Sort searches

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#20]
Searches should be able to be sorted.

-Title asc/desc on click
-DateTime asc/desc on click
-(tags ex. 'User:', 'Date:', ... if time enough)

Parent: #12

**Comment by axd1967** [comment]
careful, filtering is not the same as sorting:
- to filter = show a subset of results
- to sort = sort that (sub)set somehow

**Comment by ZiggyMaes** [comment]
Okay, so I guess the search itself (#12) would qualify as a filter then. This issue has the purpose of sorting the resulting data.

**Comment by axd1967** [comment]
indeed. searching, sorting and filtering are three different beasts.

**Comment by ZiggyMaes** [comment]
No time to implement
