### ISSUE TITLE
Create use case

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#25]
Create a use case to visualize the functional analysis of the project.

**Comment by ZiggyMaes** [comment]
@axd1967 Can you suggest software to design this use case? Or shall I write it down in plain text ( we obviously have the assignment document already, so I guess no?)?

**Comment by axd1967** [comment]
- (I liked StarUML http://sourceforge.net/projects/staruml/ but that is Windows, and now paying)
- a flat text file `Project/doc/usecases.md` or something (advantage over the wiki: it will evolve together with the repo code)
- list all the use cases
- see https://en.wikipedia.org/wiki/Use_case#Examples, limit to
  - Title (include an ID )
  - Brief, short description
- how about using http://www.planttext.com/planttext, and copy-paste the text in one or more text files?

**Comment by axd1967** [comment]
tip: when creating branches such as `Analysis`, usually this goes together with some task, or issue.

So, make sure to have an issue that goes with a branch. also, make a habit to name your branches like this:
`issue/<issuenumer>_sometext`, e.g.
`issue/234_analysis`

you will discover in you `.git/refs/` (look under `heads`  and `remotes`) that all your branches are grouped in a subdirectory "`issues/`". some IDE also allow to take profit from this (e.g. SourceTree).

**Comment by axd1967** [comment]
- [x] make sure that each use case refers to a GitHub issue where the use case is implemented so you are sure all use cases are covered
- [x] make sure that each issue refers to a use case (and maybe create a "use case" label, and I think your label "feature" is ok for that) so you are sure all issues are relevant. this requires to number the use cases (UC-001, UC-002); more handy is to use the issue number as use case number (UC-123 refers to issue/123).
- [x] each use case could be checklisted in a single test issue

**Comment by ZiggyMaes** [comment]
See 9863b61 for use cases, this okay? Seems good enough for this project.

**Comment by axd1967** [comment]
there are file extensions missing?

**Comment by ZiggyMaes** [comment]
Apologies: fa3a362

**Comment by axd1967** [comment]
- a user has many ratings
- a message has many ratings
- a system user is not a superuser
- a superuser is a user (otherwise a superuser cannot behave like a normal user)

**Comment by ZiggyMaes** [comment]
- System is not  a user. It is meant to illustrate that superusers can be appointed either manually by an administrator, or automatically by an automated script  ( #8 ).

Could you please indicate what part of the analysis you're referring to?

**Comment by axd1967** [comment]
- I would not say that "system IS A SuperUser", because System will never create threads, for example
- but a Superuser should also be a user, otherwise he can't participate as normal user.

![su](https://cloud.githubusercontent.com/assets/3529789/11559828/1e373b50-99bc-11e5-9777-bd1288d48cef.jpg)

**Comment by axd1967** [comment]
indeed , `system` will appoint a `Superuser`, but that is a use case; don't use inheritance (from Systemuser --> Superuser) for that.

**Comment by ZiggyMaes** [comment]
That makes sense :).

Patched cd327791dac130997a21838e02b0372e11b89f78 . Okay to merge with master?

**Comment by axd1967** [comment]
yup

**Comment by axd1967** [comment]
(btw, you removed the System user and the (promote) case? )

**Comment by axd1967** [comment]
careful: there are also changes in the other diagram:
(see remote 64fafe53cfa443986e2c2cb085655713794040c2)

![class_analysis](https://cloud.githubusercontent.com/assets/3529789/11562564/f83b3330-99ce-11e5-8aa6-456de500b831.png)

**Comment by ZiggyMaes** [comment]
Added relation between user and rating (93aab3ca9b2075274292a91bd89165fdc4602f9f). Did not implement area since all areas are static and hard scripted.

**Comment by ZiggyMaes** [comment]
Assuming closed and merging if no reply follows.

**Comment by ZiggyMaes** [comment]
Merged.

**Comment by axd1967** [comment]
(fetch 01d80be3f5f3dced2e99046472e7980c73086647 -> I've added a few more ideas)

(BTW, I can use a PyCharm/Android Studio IDE plugin : maybe there is a plugin for your IDE, check  http://plugins.jetbrains.com/plugin/?idea&id=7017)

![class_analysis](https://cloud.githubusercontent.com/assets/3529789/11575057/75ba9bbc-9a0f-11e5-803a-b9175d2e3aec.png)
![use_cases](https://cloud.githubusercontent.com/assets/3529789/11575058/75bfdd0c-9a0f-11e5-9750-73063194472f.png)

**Comment by axd1967** [comment]
about Area: you probably need to add two fields to `User` class
fetch!
![clipboard01](https://cloud.githubusercontent.com/assets/3529789/11575547/e23cb016-9a11-11e5-8ebe-dea959995324.png)

**Comment by ZiggyMaes** [comment]
Thanks! :) I cannot seem to find your commit though, are you referring to 76e01ee ?

**Comment by ZiggyMaes** [comment]
I'm still having doubts regarding the area class. The properties you mention are irrelevant since they are hardcoded directly into the html. I'm not dynamically loading any area content (except for the messages). The only good reason I can think of for creating a separate area class, is if we had any plans to increase the amount of available domains. But since we're definitely not doing that, I fail to see any purpose for the extra class.

**Comment by axd1967** [comment]
you will have to refer to specific areas from user records (area1, area2). now you are using strings for that, but you will have to store the area information "somehow", probably in a directory, or in a table.

when I write "class", I don't mean that you have to end up with a class in your _code_ (C#, C++, Java, db table...). A class in _analysis_ is simply a concept, an object that has properties. In the implementation there might be no physical class, but somewhere you will be able to say: "here is an (instance of an) area" and be able to refer to it (eg by using its name, as you intend to do). therefore, that is an object, that has properties, and thus it is an instance of a class, and that is how you can document it in the Class analysis diagram.

**Comment by ZiggyMaes** [comment]
Thank you for the clarification! :+1:

**Comment by axd1967** [comment]
(idem here, add a link to the Use case diagram in the top comment. not necessary)
