### ISSUE TITLE
Can we implement e-mail support

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#28]
We have not seen any method for sending automated e-mails (for registration, password resets, ...). It would introduce the need for a SMTP/IMAP service I think...

**Comment by axd1967** [comment]
consider creating a tag "extra", for features that are not part of the assignment, but could be good/nice-to-have/etc...

and deal with them later: be careful for [feature creep](https://en.wikipedia.org/wiki/Feature_creep).

**Comment by ZiggyMaes** [comment]
We can implement this, but will require a SMTP server. Marking this as extra.

**Comment by ZiggyMaes** [comment]
Done
