### ISSUE TITLE
Create MS-SQL database

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#3]
Use #2 for DB schematics...

**Comment by ZiggyMaes** [comment]
Done, see 2b9aff07057c90c2e0686ec0e9b66d7ac1a45091 .

**Comment by axd1967** [comment]
about the DB structure:
- Domain also needs an image (disk path) field
- Maybe Domain should be better called Area
- Message.UserID should be an int, (just as in Message.UserID)
- there is no way to record what areas a user has chosen

take a close look at https://github.com/axd1967/mz/blob/comments_on_diagrams/Project/Doc/Analysis/class_analysis.png

**Comment by ZiggyMaes** [comment]
Yes, made some mistakes during DB creation. Recreating now, fighting against some SQL SMS bugs though that prevent me from creating relations...

**Comment by ZiggyMaes** [comment]
- They don't need an image field because images are being loaded statically, not using the DB. The reason I implemented the Domain table was to provide a division for the forums.
- Renamed the Domain table to Area
- userID is an int? Not sure what you're referring to? https://gyazo.com/1424fdcbbc15331adefbc8abb8f65659
- Was basing myself on an old diagram... Thanks!

**Comment by axd1967** [comment]
yes, in Message, userid is an int, but it should also be an int in Rating (sorry wrote "Message")

**Comment by ZiggyMaes** [comment]
Good catch, thank you!

**Comment by ZiggyMaes** [comment]
Pushed 5ea741abe0f763efd4921d600d65dddd9a21f311

Relations: https://gyazo.com/a98da8961a9f46f2ad5a418f842ef5f3

**Comment by axd1967** [comment]
- that relations pic looks good, add it to the Doc folder.
- careful for the social provider stuff, make sure you know what you are doing.

**Comment by ZiggyMaes** [comment]
Roger roger! 3454b6c34bf6d0926bf650e3780130004d35b9bd
