### ISSUE TITLE
Registration mandatory to access interest areas

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#6]
Users are required to register/authenticate if they are to access two interest areas. Unauthenticated users cannot access any area. #4 #5

**Comment by ZiggyMaes** [comment]
Additional information: the user needs to receive a message that it can only access two areas. Any two areas can be chosen (either let him choose, or just use the first two areas he will access).

How can we enforce this?

**Comment by axd1967** [comment]
- unauth users can select the start page of _one_ area
- auth users can select up to two areas
  - as soon as two are selected, the other areas are greyed out
  - if less than two areas are selected, all areas can be selected

**Comment by ZiggyMaes** [comment]
I think unauth users can select the start page of **all** interest domains. This page is used to convince the user to continue in this area. (see issue #18 )

**Comment by axd1967** [comment]
and ONE area should also be OK.

**Comment by ZiggyMaes** [comment]
Implemented :)
