### ISSUE TITLE
Access levels

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#7]
We need three site access levels: user, super-user and administrator.

User: access to two interest areas
Super-user: user access + can start new threads
Administrator: full access

**Comment by axd1967** [comment]
:exclamation: this is W3, but you might already need this in #11  (currently in W2!)

**Comment by ZiggyMaes** [comment]
This is extended functionality for the forum. Technically, it is merely an addition to a control structure. That  said, moving all registration/authentication related issues to week 2 for workload balancing.

**Comment by ZiggyMaes** [comment]
Complete
