### ISSUE TITLE
Super-user selection

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#8]
How do users get the super-user statute?

Have X ratings?
Registration time?

More unique:
Verified aviation professional

**Comment by ZiggyMaes** [comment]
#7

**Comment by axd1967** [comment]
admins could also promote users to superusers (and back)

**Comment by ZiggyMaes** [comment]
Yes they definitely should, but the assignment also implies an automated system. I was thinking of implementing a script that promotes them to superuser after 5 comments (number for the sake of the exercise).

**Comment by axd1967** [comment]
(that's why manual promotion could be an "**extra**" feature -> you can add that if you have time left)

**Comment by axd1967** [comment]
- every night, the server runs a script 

suggestions:
- a user becomes superuser when has average rating of 2+?
- superuser is demoted if average rating below 1?
- (administrator is always a superuser)

**Comment by ZiggyMaes** [comment]
Instead of a nightly script I could just implement a quick control structure that immediately assigns the superuser status? (also because we haven't seen how to do actually write something like this).

**Comment by axd1967** [comment]
yup - after every rating change, should work.

**Comment by ZiggyMaes** [comment]
Implemented & working
