### ISSUE TITLE
Administrators can view site statistics

### ISSUE THREAD

**Issue by ZiggyMaes** [ZiggyMaes/Labos-ServersideApplications#9]
Administrators should be able to see certain statistics that are relevant and useful.
- [ ] Where do people enter (referral + entry location) and leave (last know location) the site?
- [ ] How many users are 'subscribed' to each interest area?
- [ ] View user activity (timeline, area, ...).
- [ ] how much rating activity is going on? (number of rating actions per day and/or per area)
- [x] how much users are registered over time
- [ ] how much reports are ther over time/area (reported users, blocked users, reported messages, hidden messages)

**Comment by axd1967** [comment]
which stats? checklist all stats that will be available.

**Comment by ZiggyMaes** [comment]
I was putting them in a separate issues, but a checklist will indeed be easier

**Comment by axd1967** [comment]
add it in the top comment, so you don't have to scan the entire conversation thread

**Comment by axd1967** [comment]
**edit 11/12 ZM: moved to top comment**
(no need to implement all of them - this is to help with ideas)

_(if you agree with a comment like this, feel free to edit and move the content to the top comment and delete this comment. don't do this in your future work place, or people might not appreciate such actions). this will add a progress bar when viewing the issue from a issue list, look at issue 16  in https://github.com/ZiggyMaes/NMCT-Server-Side-Applications/issues_

**Comment by ZiggyMaes** [comment]
Implemented basic stuff. Will optimize later.
